### ISSUE TITLE
About ADB and memory leak

### ISSUE THREAD

**Issue by hlopezrd** [loentar/axis2c-unofficial#21]
Hi,
I'm having a hard time with AXIS2C and memory leak. I was checking a post in stackoverflow that said:
>Please note ADB (and generated services) has memory leaks, and it's not fixed in unofficial branch.

Is this true? do I have any way to fix it?
Thanks in advance for any help.
regards.

**Comment by loentar** [comment]
Only if you fix codegeneration yourself.
Apache discarded Axis2/C project.. And this project mostly for support of existing software developed on axis2c. 

If you look for REST/SOAP/JSON webservices framework it's better to take something other.

**Comment by hlopezrd** [comment]
Thanks a lot for the response.
And is really bad to hear it, I need to update a project that have a lot of "codegeneration" code.
Any suggestion for another tool that really work?
Thanks again.

**Comment by loentar** [comment]
If you are not restricted to language, you may choose Java or Python. These has a lot of ready for production frameworks.

**Comment by hlopezrd** [comment]
Thanks, Dmitry, but we already use C++ to link and to interact with other services in the application. Will be hard move this to another language. I already manage to use AXIS2C UO with Staff and I think will be our solution for some time until we move to another framework. I had some minors issue with the compiler because we compile using Sun C (CC) and Staff was compiled with g++. But in a meanwhile I think will fine this way.
Thanks again.
Regards.
