### ISSUE TITLE
Compilation error when building for httpd

### ISSUE THREAD

**Issue by abhayasingh** [loentar/axis2c-unofficial#23]
Below is my configuration command
./configure --enable-trace --enable-openssl --with-apache2=/home/cubot/Downloads/httpd-2.4.27/include --with-apr=/home/cubot/Downloads/httpd-2.4.27/srclib/apr/include --prefix=$thisdir/bin_output --enable-libxml2=yes
after running make command getting below error
In file included from /home/cubot/Downloads/httpd-2.4.27/include/ap_config.h:25:0,
                 from /home/cubot/Downloads/httpd-2.4.27/include/httpd.h:44,
                 from mod_axis2.c:19:
/home/cubot/Downloads/httpd-2.4.27/include/ap_hooks.h:40:23: fatal error: apr_hooks.h: No such file or directory
compilation terminated.

can someone help me with this

**Comment by loentar** [comment]
I believe that `/home/cubot/Downloads/httpd-2.4.27/srclib/apr/include` isn't correct apr path.

**Comment by abhayasingh** [comment]
looks okay to me, able to get all apr hearders
[cubot:~/Downloads/httpd-2.4.27$]ls /home/cubot/Downloads/httpd-2.4.27/srclib/apr/include/
apr_allocator.h  apr_errno.h      apr_general.h       apr.h.in       apr_lib.h         apr_pools.h       apr_shm.h       apr_tables.h         apr_time.h     private
apr_atomic.h     apr_escape.h     apr_getopt.h        apr.hnw        apr_mmap.h        apr_portable.h    apr_signal.h    apr_thread_cond.h    apr_user.h
apr_cstr.h       apr_file_info.h  apr_global_mutex.h  apr.hw         apr_network_io.h  apr_proc_mutex.h  apr_skiplist.h  apr_thread_mutex.h   apr_version.h
apr_dso.h        apr_file_io.h    apr.h               apr.hwc        apr_perms_set.h   apr_random.h      apr_strings.h   apr_thread_proc.h    apr_want.h
apr_env.h        apr_fnmatch.h    apr_hash.h          apr_inherit.h  apr_poll.h        apr_ring.h        apr_support.h   apr_thread_rwlock.h  arch

**Comment by loentar** [comment]
but it doesn't contain required apr_hooks.h.. try to find it and place to include path.

And why do you compile apache2 from source code, it is not better than using of package manager?

**Comment by abhayasingh** [comment]
"but it doesn't contain required apr_hooks.h.. " 
-- apr_hooks.h is available in apache2/include/, I have checked my old version of axis2c, where i was compiling with same configuration( apache httpd 2.2.x and apr 1.0), apr_hooks.h was in apache/include and not in apr/include and I wasn't getting this error.

"And why do you compile apache2 from source code"
I have my own module written in apache httpd, thats is why i compile apache2 from source code, on other hand when i read 'INSTALL' instruction of axis2c code in section '3. Installing Apache2 Web Server Integration Module (mod_axis2)', its mentioned configuration command like below
 ./configure --with-apache2="<apache2 include files location>"
                         --with-apr="<apr include files location>"
                         [other configure options]
just followed that

**Comment by abhayasingh** [comment]
Finally able to compile the code, not sure what was the problem, but I picked up what you said and compiled this code with apache/include provided by package installation and not from apache httpd source code. And it solved the compilation problem.
Please let me know if you understood the problem and thanks for your help.
